server:
  port: 8080

spring:
  application:
    name: khoj
  tomcat:
    max-http-form-post-size: 104857600
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.service.cognito.user-pool-id}
      client:
        registration:
          cognito:
            client-id: 77rk9usn4he5h8v7oec6oapa64
            client-secret: vs1tkap0ocd4se0sc5b445cu3gj7fogj1g3no4c2ve4t8tmb0uo
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
        provider:
          cognito:
            issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.service.cognito.user-pool-id}

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  accessKey: AKIAZI2LDEGGM2252YOC
  secretAccessKey: 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
  region: us-east-1
  service:
    cognito:
      user-pool-id: ${aws.region}_E4Msk8R6D
    s3:
      region: us-east-2
      bucketName: ${spring.application.name}bucket
      file:
        base-directory: ${spring.application.name}/files
    dynamodb:
      region: us-east-1
      table-name: user



