spring:
  application:
    name: khoj
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 77rk9usn4he5h8v7oec6oapa64
            client-secret: vs1tkap0ocd4se0sc5b445cu3gj7fogj1g3no4c2ve4t8tmb0uo
        provider:
          cognito:
            issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.region}_E4Msk8R6D

aws:
  region: us-east-1
